### PR TITLE
add utilitiy functions + enable 301 redirection feature

### PR DESCRIPTION
**Pull request by geektortoise**
Also add the "waiting for core starting" feature 
+
a specific "CytomineConnection" when uploading a file

### CODE REVIEW

**Comment by urubens** [comment]
Even after merging other PRs, this one is still failing :disappointed: 

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/Cytomine.java:[589,44] cannot find symbol
  symbol:   method getValue()
  location: variable status of type be.cytomine.client.models.Job.JobStatus
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/Cytomine.java:[593,44] cannot find symbol
  symbol:   method getValue()
  location: variable status of type be.cytomine.client.models.Job.JobStatus
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/sample/ImageExample.java:[64,38] no suitable method found for uploadImage(java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,<nulltype>,boolean)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,java.util.Map<java.lang.String,java.lang.String>,boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/sample/CropExample.java:[35,17] cannot find symbol
  symbol:   method indexToRetrieval(long,long,java.lang.String)
  location: variable cytomine of type be.cytomine.client.Cytomine
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/sample/UploadExample.java:[49,35] no suitable method found for uploadImage(java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,<nulltype>,boolean)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,java.util.Map<java.lang.String,java.lang.String>,boolean) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 5 errors 
```

**Comment by urubens** [comment]
Even after merging other PRs, this one is still failing :disappointed: 

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/Cytomine.java:[589,44] cannot find symbol
  symbol:   method getValue()
  location: variable status of type be.cytomine.client.models.Job.JobStatus
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/Cytomine.java:[593,44] cannot find symbol
  symbol:   method getValue()
  location: variable status of type be.cytomine.client.models.Job.JobStatus
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/sample/ImageExample.java:[64,38] no suitable method found for uploadImage(java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,<nulltype>,boolean)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,java.util.Map<java.lang.String,java.lang.String>,boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/sample/CropExample.java:[35,17] cannot find symbol
  symbol:   method indexToRetrieval(long,long,java.lang.String)
  location: variable cytomine of type be.cytomine.client.Cytomine
[ERROR] /home/travis/build/Cytomine-ULiege/Cytomine-java-client/src/main/java/be/cytomine/client/sample/UploadExample.java:[49,35] no suitable method found for uploadImage(java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,<nulltype>,boolean)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method be.cytomine.client.Cytomine.uploadImage(java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.String,java.util.Map<java.lang.String,java.lang.String>,boolean) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 5 errors 
```

**Comment by geektortoise** [comment]
Ok. I think I see what is the problem !
I will try to fix it soon. :-)

**Comment by urubens** [comment]
I tried to merge company master branch into ULiege master: https://github.com/Cytomine-ULiege/Cytomine-java-client/tree/sync-company/master-merge 

Not tested yet, but it compiles, so I expect it takes code from this PR, with what was missing. And probably we can close this PR.

**Comment by geektortoise** [comment]
Yes
